### ISSUE TITLE
Move to version of Java that has truststore that trusts letsencrypt certs

### ISSUE THREAD

**Issue by donaldmcintosh** [donaldmcintosh/triki#20]
[WARN] 2018-10-17 13:58:09,080 org.eclipse.jetty.servlet.ServletHandler doHandle - /auth/indie
org.apache.cxf.interceptor.Fault: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)

**Comment by donaldmcintosh** [comment]
Moved to latest Java 8 and this works now.
